spring:
  application:
    name: ObserverPatternHexagonalDDD
  cache:
    cache-names: payments
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m,recordStats

logging:
  level:
    org.springframework.cache.interceptor: TRACE

resilience4j.retry:
  instances:
    paymentRetry:
      max-attempts: 2
      wait-duration: 200ms

resilience4j.circuitbreaker:
  instances:
    paymentCircuitBreaker:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      minimumNumberOfCalls: 5
      failureRateThreshold: 20
      waitDurationInOpenState: 3s
      permittedNumberOfCallsInHalfOpenState: 2

