app:
  startup-runner:
    enabled: true
spring:
  application:
    name: DecoratorPatternInPersistanceHexagonalDDD
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  cache:
    cache-names: reservations
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m,recordStats

  main:
    web-application-type: servlet