app:
  startup-runner:
    enabled: true
spring:
  application:
    name: ObserverPatternCQRSHexagonalDDD
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
  data:
      mongodb:
        uri: mongodb://localhost:27017/testdb
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration
de.flapdoodle.mongodb.embedded.version: 6.0.5

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE
